"""empty message

Revision ID: 58c01c2cfdd2
Revises: e56c2ffb4c49
Create Date: 2018-11-12 09:09:14.651239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58c01c2cfdd2'
down_revision = 'e56c2ffb4c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
