"""empty message

Revision ID: 66e5cc80a503
Revises: 615ce05c5949
Create Date: 2018-11-09 17:36:22.505661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e5cc80a503'
down_revision = '615ce05c5949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'last_updated')
    # ### end Alembic commands ###
