"""empty message

Revision ID: 48760dd7fdc2
Revises: 6ba20c107417
Create Date: 2018-11-09 20:38:03.220597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48760dd7fdc2'
down_revision = '6ba20c107417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('user_files', sa.Column('updated_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('user_files', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('last_updated', mysql.DATETIME(), nullable=True))
    op.drop_column('user_files', 'updated_on')
    op.drop_column('user_files', 'created_on')
    # ### end Alembic commands ###
