"""empty message

Revision ID: 5da77f3ada51
Revises: 48760dd7fdc2
Create Date: 2018-11-09 20:40:05.330842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5da77f3ada51'
down_revision = '48760dd7fdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_files', 'updated_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_files', sa.Column('updated_on', mysql.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###
