"""empty message

Revision ID: a6e58945c960
Revises: 
Create Date: 2018-10-31 20:41:52.144345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6e58945c960'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('symbol', table_name='member')
    op.drop_table('member')
    op.add_column('user', sa.Column('first_name', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=80), nullable=True))
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.create_table('member',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('symbol', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_unicode_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_index('symbol', 'member', ['symbol'], unique=True)
    # ### end Alembic commands ###
