"""empty message

Revision ID: b2df6837c19e
Revises: 
Create Date: 2018-11-01 10:56:39.690815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2df6837c19e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=128), nullable=True))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=60), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=60), nullable=True))
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    # ### end Alembic commands ###
